### ISSUE TITLE
No sender ID handling is present

### ISSUE THREAD

**Issue by djkazic** [klaus7/jfastnet#1]
If you create multiple clients to connect to a server, they all default to a sender ID of 1, so only one client can connect.

The client should be able to allocate a new senderID so that the server does not kick off any additional clients that try to connect, as there is no way to find out what is the next available ID from the server at this time.

So if a server exists with connections {1, 2, 3, 4}, currently a client has to try connecting on each ID until it get a successful connection @ ID 5.

If there is a workaround, please let me know.

**Comment by klaus7** [comment]
You are correct. In our game we retrieve a unique player id first via an authentication webservice and we use this id to connect to the server, that's why I didn't see this problem before.

I will implement an automatic assignment of a sender id if it's not set. This is probably a good default behavior. 

Thanks for your feedback!

**Comment by djkazic** [comment]
Hello Klaus,

Thank you for making me realize I'm not crazy haha.

Is there any way I could work with you on this? My application is peer to
per and so cannot have a central point of failure. Could the server send
back an assigned client ID somehow? Or maybe have the client ID be unique
to each machine, based on some attribute of the machine?

**Comment by klaus7** [comment]
I would say it's best to let the server assign an id and send it back to the client. I'll look into that.

P2P communication is not implemented for now, but feel free to fork and modify/improve the library. And if you plan to do so, please make a pull request once you're done, so we can make the new features available to others in the main repository too.
