### ISSUE TITLE
Suggestion: can we make msgId use unsigned short

### ISSUE THREAD

**Issue by implicit-invocation** [klaus7/jfastnet#3]
I noticed that the current IdProvider's using long for id (https://github.com/klaus7/jfastnet/blob/master/src/main/java/com/jfastnet/idprovider/IIdProvider.java)  
Does that make header overhead bigger?  
Do you think we should use short and check for wrap around in `compare` (check difference is less than 1⁄2 the maximum)?

**Comment by klaus7** [comment]
No, this doesn't make the header bigger. Have a look at Kryo's class `com.esotericsoftware.kryo.io.Output#writeVarLong`

Kryo is very efficient with both serialization speed and size. Also have a look at the test method: `com.jfastnet.messages.MessageTest#sizeTest` - here you'll see that a naked message (that contains an `int` and a `long` field!) is just 4 bytes long. :)
